# Generated by Django 4.0.6 on 2022-11-02 05:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 2, 5, 22, 26, 395994, tzinfo=utc)),
        ),
    ]
