# Generated by Django 4.0.6 on 2022-11-02 05:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_posts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 2, 5, 24, 27, 981800, tzinfo=utc)),
        ),
    ]
