# Generated by Django 4.0.6 on 2022-11-05 17:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_posts_options_alter_author_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 5, 17, 17, 30, 948981, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
