# Generated by Django 4.0.6 on 2022-11-08 10:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_posts_date_alter_posts_image_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 8, 10, 40, 55, 760172, tzinfo=utc)),
        ),
    ]
