# Generated by Django 4.1.3 on 2023-01-07 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_posts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 7, 13, 23, 18, 661996, tzinfo=datetime.timezone.utc)),
        ),
    ]
